    frame_color = "#928374"

[urgency_low]
    background = "#282828"
    foreground = "#ebdbb2"
    highlight = "#83a598"
    timeout = 6

[urgency_normal]
    background = "#282828"
    foreground = "#ebdbb2"
    highlight = "#83a598"
    timeout = 8

[urgency_critical]
    background = "#fb4934"
    foreground = "#282828"
    frame_color = "#fb4934"
    highlight = "#282828"
    timeout = 0
