    frame_color = "#fe8019"

[urgency_low]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#928374"
    highlight = "#fe8019"
    timeout = 6

[urgency_normal]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#fe8019"
    highlight = "#fe8019"
    timeout = 8

[urgency_critical]
    background = "#282828"
    foreground = "#ebdbb2"
    frame_color = "#fb4934"
    highlight = "#fb4934"
    timeout = 0
