set $backgroundColor #282828
set $selection #3c3836
set $comment #928374
set $foreground #ebdbb2

set $yellow #fabd2f
set $orange #fe8019
set $red #fb4934
set $magenta #d3869b
set $blue #83a598
set $cyan #8ec07c
set $green #b8bb26
