    frame_color = "#cba6f7"

[urgency_low]
    background = "#1e1e2e"
    foreground = "#cdd6f4"
    highlight = "#cba6f7"
    timeout = 6

[urgency_normal]
    background = "#1e1e2e"
    foreground = "#cdd6f4"
    highlight = "#cba6f7"
    timeout = 8

[urgency_critical]
    background = "#f38ba8"
    foreground = "#1e1e2e"
    frame_color = "#f38ba8"
    highlight = "#1e1e2e"
    timeout = 0
