    icon_theme = "ZorinPurple-Dark, Adwaita, hicolor"
    frame_color = "#ff79c6"

[urgency_low]
    background = "#282a36"
    foreground = "#f8f8f2"
    frame_color = "#6272a4"
    highlight = "#ff79c6"
    timeout = 6

[urgency_normal]
    background = "#282a36"
    foreground = "#f8f8f2"
    frame_color = "#ff79c6"
    highlight = "#ff79c6"
    timeout = 8

[urgency_critical]
    background = "#282a36"
    foreground = "#f8f8f2"
    frame_color = "#ff5555"
    highlight = "#ff5555"
    timeout = 0
