    frame_color = "#6272a4"

[urgency_low]
    background = "#282a36"
    foreground = "#f8f8f2"
    highlight = "#6272a4"
    timeout = 6

[urgency_normal]
    background = "#282a36"
    foreground = "#f8f8f2"
    highlight = "#6272a4"
    timeout = 8

[urgency_critical]
    background = "#ff5555"
    foreground = "#f8f8f2"
    frame_color = "#ff5555"
    highlight = "#f8f8f2"
    timeout = 0
